# Generated by Django 3.2.16 on 2022-11-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='testimage.example.com', max_length=255),
            preserve_default=False,
        ),
    ]
