# Generated by Django 4.1.2 on 2022-10-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('price', models.FloatField()),
                ('product_url', models.CharField(max_length=255)),
                ('product', models.ManyToManyField(to='product.product')),
                ('shop', models.ManyToManyField(to='shop.shop')),
            ],
        ),
    ]
