# Generated by Django 3.2.16 on 2022-12-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product_id',
            new_name='product',
        ),
    ]
