# Generated by Django 3.2.16 on 2022-11-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_url', models.CharField(max_length=255)),
                ('search_param', models.CharField(max_length=255)),
                ('parser_type', models.CharField(choices=[('soup', 'Soup'), ('webdriver', 'Webdriver')], max_length=20)),
            ],
        ),
    ]
